Replaced fire with Argparse
fredysomy/pysonDB pull request #44
Opened 2021-09-30 14:46 UTC by Flodur871

I replaced fire with Argparse as discussed in #38. 
Additionally I added some missing docstrings and made small fixes to the code.

2021-09-30 14:58 UTC, Adwaith-Rajesh commented
@Flodur871 thanks for the contribution, You PR will be merged by tomorrow.

2021-09-30 15:11 UTC, Adwaith-Rajesh requested changes
you can ignore the type hints if you want to, but the rest of the thing are needed for the long run

2021-09-30 15:11 UTC, Adwaith-Rajesh commented on pysondb/cli.py
> +    parser = argparse.ArgumentParser()
The `ArgumentParser` should now accept `argv` as an argument
`argparse.ArgumentParser(argv)`

2021-09-30 15:11 UTC, Adwaith-Rajesh commented on pysondb/cli.py
> +def main():
`def main() -> int`

2021-09-30 15:11 UTC, Adwaith-Rajesh commented on pysondb/cli.py
>      main()
`raise SystemExit(main())` So that the exit codes for that last command is stored in the terminal session

2021-09-30 15:48 UTC, fredysomy requested changes
hey @Flodur871 It will be great if you can update the [docs](https://fredysomy.me/pysonDB/docs/cli) with the updated arguments.

2021-09-30 15:55 UTC, fredysomy commented
do you guys find any alternatives to beautifultable

2021-09-30 15:59 UTC, Adwaith-Rajesh commented
> do you guys find any alternatives to beautifultable

https://stackoverflow.com/a/26937531 or we have to use python string formatting

2021-09-30 16:10 UTC, fredysomy commented
I was thinking of reducing some more depency size. And at the same time
display method should be there as a visual feedback for the developer.

Is it complicated using format strings

On Thu, 30 Sep 2021, 9:29 pm Adwaith Rajesh, ***@***.***>
wrote:

> do you guys find any alternatives to beautifultable
>
> https://stackoverflow.com/a/26937531 or we have to use python string
> formatting
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/fredysomy/pysonDB/pull/44#issuecomment-931454136>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APXKHAAJW2WV5E27742Y3DDUESCNTANCNFSM5FCQT4TA>
> .
>

2021-09-30 16:26 UTC, Flodur871 commented
> hey @Flodur871 It will be great if you can update the [docs](https://fredysomy.me/pysonDB/docs/cli) with the updated arguments.

Will do

2021-10-01 03:09 UTC, Adwaith-Rajesh approved these changes
nice work, thnx for the contributing.

2021-10-01 03:21 UTC, fredysomy approved these changes

2021-10-01 03:21 UTC, fredysomy commented
Thanks for the Contribution.🤩

2021-10-01 03:22 UTC, merged