Fix .find bug
fredysomy/pysonDB pull request #47
Opened 2021-09-30 19:33 UTC by LyndonFan

Fixed the bug with .getById function. Also updated the deprecation warning in .find and added tests for .find function.
Would it be better to have the tests call getById instead?

2021-09-30 20:01 UTC, fredysomy commented
I will get back to it, in a few hours.

And BTW thanks for the Contribution 🤩

2021-09-30 20:03 UTC, fredysomy requested changes
It would be better to do the testing with getById.

Can you change it.

2021-09-30 20:18 UTC, LyndonFan commented
Done!

2021-10-01 03:28 UTC, fredysomy approved these changes

2021-10-01 03:29 UTC, merged